name: Deploy Portfolio to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # STEP 1 - Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # STEP 2 - Upload static files as artifact
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."   # root directory (index.html, style.css, mypic.jpeg)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # STEP 3 - Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
